sudo: false
cache:
  directories:
    - ~/.npm
notifications:
  email: false
language: node_js
node_js:
  - "10"
  - "8"
  - "6"
before_install:
  - npm install -g npm
before_script:
  - npm install -g grunt-cli
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
