sudo: false
cache:
  directories:
    - node_modules
notifications:
  email: false
language: node_js
node_js:
  - "4"
  - "6"
  - "8"
before_install:
  - npm install -g npm
before_script:
  - npm install -g grunt-cli
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
